[tox]
envlist = py39
skipsdist = True

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONHASHSEED = 0
commands = 
    flake8
    pytest --cov=my_module --cov-report term-missing

[flake8]
max-line-length = 120
exclude = .tox,.git,__pycache__,docs/source/conf.py,build,dist
